### ISSUE TITLE
Properties under a "transition" aren't prefixed

### ISSUE THREAD

**Issue by brian-c** [LeaVerou/prefixfree#8] opened 2011-10-14 19:31 UTC
For example, `transition: transform 0.25s ease-in-out;`
becomes `-moz-transition: transform 0.25s ease-in-out;`.

I expected `-moz-transition: -moz-transform 0.25s ease-in-out;`

**Comment by LeaVerou** [comment] 2011-10-14 19:32
Ouch, that won't be as easy as some other bugs to fix. 
Which properties accept properties as values? Is it only transition? Can't think of others off the top of my head.

**Comment by brian-c** [comment] 2011-10-14 20:10
Hey, looks like that got it! Thanks a lot.

Transition is the only property-as-value property I can think of too. If any more come to mind I'll let you know.

**Comment by LeaVerou** [comment] 2011-10-14 20:12
Yes, I know it's fixed now, but it's a quick and dirty fix and I'm not very comfortable with it.

The problem is that now it doesn't require properties to have a colon afterwards to be prefixed, so it could accidentally end up prefixing keywords, names etc that happen to have the same name as some property.
I added some code to avoid accidentally prefixing stuff in URLs, but the risk still stands for any other arbitrary string (e.g. animation names, counter names etc).
Can't think of any realistic use case that would break right now, but you never know.

I'll leave the fix as-is for now and see if anyone complains about something broken and I'll take it from there if that happens.

**Comment by brian-c** [comment] 2011-10-14 20:17
Ah, I see. `#foo:after {content: "transition"}` ends up with the content "-moz-transition" now.

**Comment by LeaVerou** [comment] 2011-10-14 20:18
Yup, that too. Was that actually in your CSS?

**Comment by brian-c** [comment] 2011-10-14 20:32
Hah, no, I was just testing that regexp.

**Comment by LeaVerou** [comment] 2011-10-14 20:33
I'm currently working on a more robust solution, cause that one makes me very uncomfortable.

**Comment by LeaVerou** [comment] 2011-10-14 20:41
And there it is. It increased file size by 0.2KB but oh well.

**Comment by panayiotisa** [comment] 2011-10-15 16:06
You 're still missing calc() and fwiw element()

**Comment by LeaVerou** [comment] 2011-10-15 18:17
calc is there, line 238. 
As for element, yeah I know, I'll add it soon.

Also, both are irrelevant with this bug, so closing this.

**Closed as completed** 2011-10-15 18:17 UTC
Labels: Fixed
