### ISSUE TITLE
Support for LESS

### ISSUE THREAD

**Issue by Anahkiasen** [LeaVerou/prefixfree#52] opened 2012-02-23 16:09 UTC
Hi,
I was wondering, is there any way to make Prefixfree compatible with Less.js ? Make it add prefixes to .less files compiled on-the-fly ?

**Comment by DavidBradbury** [comment] 2012-04-12 17:54
I personally haven't tested this yet, but I imagine Less.js should work just fine with the Dynamic DOM plugin. If I have time later I'll test it out and see the results.

**Comment by DavidBradbury** [comment] 2012-04-12 21:46
Seems to work just fine:

**index.htm**

``` HTML
<!DOCTYPE HTML>
<html lang=en>
<meta charset=UTF-8>
<title>-prefix-free + LESS.js</title>

<link rel="stylesheet/less" type="text/css" href="style.less">

<script src="prefixfree.min.js"></script>
<script src="prefixfree.dynamic-dom.min.js"></script>
<script src="less-1.3.0.min.js" type="text/javascript"></script>

<h1>-prefix-free + LESS.js</h1>
<p>Testing <a href="#">transitions using less and -prefix-free.</a>
```

``` CSS
@my-blue: #36a;

body {
    font-family: Arial, sans-serif;
    text-align: center;
}

h1 {
    font-size: 32px;
    font-weight: bold;
}

p {
    font-size: 16px;
    transition: all 1s;
    padding: 4px 0;
    a {
        padding: 3px;
        font-weight: bold;
        color: @my-blue;
        text-decoration: none;
        text-shadow: 0 0 0 #fff;
        transition: all 1s;

        &:hover { 
            color: #fff;
            text-shadow: 0 0 5px @my-blue;
        }
    }
    &:hover {
        background: #333;
        color: #fff;
    }
}
```

**Comment by tgecho** [comment] 2012-04-20 16:11
It works fine unless you turn on less' watch mode. The plugin doesn't pick up the refresh, so all of the prefixing is lost.

**Comment by DavidBradbury** [comment] 2012-04-20 18:26
Excuse me if I'm mistaken, but how is -prefix-free supposed to recognize that something has changed on the server-side? In this case it sounds like LESS is changing information without informing everyone else.

**Comment by tgecho** [comment] 2012-04-20 18:47
Less is already taking care of checking the server for updates and refreshing the generated css. I don't know exactly how it does this refresh, and I'm sure it's something weird that -prefix-free can't be expected to pick up without a little extra code. I don't understand either enough to do that atm, but I figured I'd just add some detail about exactly what works (basic less + -p-f) and what doesn't (less in watch mode + -p-f).

**Comment by lunelson** [comment] 2012-04-22 08:22
This is encouraging. An alternative here might be to use a program like LiveReload to pick up the refresh for you, and this has advantages as it watches your entire folder for any changes at all, not just LESS file updates.

AFAIK, LESS' watch mode basically just reloads the stylesheet in a constant cycle, so LiveReload may actually be technically more efficient.

**Comment by LeFouineur** [comment] 2012-05-08 20:08
That problem can also occur when you're generating the CSS dynamically ! Not only with **LESS**.
 And apparently, calling the method :

``` Javascript
StyleFix.process();
```

is working _perfectly_ (at least in the few tests I have done until now)

A little exemple of a script draft to put in your page/code could be something like that :

``` Javascript
setInterval( StyleFix.process, less.watchTime);
```

It would retrieve the timer set by less.watch() and parse again the CSS code after that time.
It's not really optimized (could be slow on large CSS files and there is a delay between the display of the new **LESS** CSS and the parsing of **PreFixFree**), but it can at least show you how it will render.

You can always slow down or stop the timer of **LESS** for when you want to verify if the prefix and CSS render correctly.

**Comment by LeaVerou** [comment] 2012-05-24 01:50
Nice discussion, thanks @DavidBradbury for responding.
Closing the issue as it's not a bug.

**Closed as completed by LeaVerou** 2012-05-24 01:50 UTC
