### ISSUE TITLE
box-shadow gets prefixed even when it shouldn't

### ISSUE THREAD

**Issue by Jojaba** [LeaVerou/prefixfree#24] opened 2011-11-05 18:09 UTC
IE10 version tested: 10.0.8102.0
When prefixing the box-shadow propertie (like -prefix-free do it on IE10), this propertie doesn't work.
Example that doesn't work for IE10:
    -ms-box-shadow(#6D6D6D 2px 2px 4px)
This works for IE10:
    box-shadow(#6D6D6D 2px 2px 4px)

You can see this issue on that page: http://jojaba.free.fr/alsacreations/prefixfree-demo/prefixfree-demo.html

Thanks for your great work

**Comment by LeaVerou** [comment] 2011-11-06 07:46
Hi Jojaba,

Can you please run these commands in the console, on a blank HTML5 file, and report back the results? I don't have access to IE10 right now.

`'boxShadow' in document.body.style`
`'msBoxShadow' in document.body.style`
`'MsBoxShadow' in document.body.style`

Thanks!

**Comment by Jojaba** [comment] 2011-11-06 10:54
Sorry, but I don't know how to do that. I can type the commands in the 
console, but how can I select document.body.style?
I typed the commands in the console for the moement without selecting 
document.body.style and get a "... is undefined" for each of these 
commands (boxShadow, msBoxShadow, MsBoxShadow)

jjb

**Comment by LeaVerou** [comment] 2011-11-06 10:55
you forgot the quotes. `'boxShadow'` not `boxShadow`.

**Comment by Jojaba** [comment] 2011-11-06 13:46
By adding the quotes I get this:
For 'boxShadow' getting "boxShadow"
For 'msBoxShadow' getting "msBoxShadow"
For 'MsBoxShadow' getting "MsBoxShadow"

I typed in the console this line:
document.body.style
I get this tree:

---

> > document.body.style
> > [object MSStyleCSSProperties] {
> >      pixelBottom : 0,
> >      pixelHeight : 0,
> >      pixelLeft : 0,
> >      pixelRight : 0,
> >      pixelTop : 0,
> >      pixelWidth : 0,
> >      posBottom : 0,
> >      posHeight : 0,
> >      posLeft : 0,
> >      posRight : 0
> >      ...
> > }
> > Add to watch
> > 
> > ---
> > 
> > By clicking on Add to watch, several properties has been displayed in 
> > wich I saw:
> > 
> > ---
> > 
> > ```
> >      boxShadow    ""
> >      msBoxAlign    ""
> >      msBoxDirection    ""
> >      msBoxFlex    ""
> >      msBoxLineProgression    ""
> >      msBoxLines    ""
> >      msBoxOrdinalGroup    0
> >      msBoxOrient    ""
> >      msBoxPack    ""
> > ```
> > 
> > ---
> > 
> > Some other ms prefixed properties are shown (but it is not easy to 
> > copy/paste the whole properties as it must be done separatly, I can do a 
> > screenshot if you want...)

jjb

**Comment by LeaVerou** [comment] 2011-11-06 13:50
No, I meant type the whole thing in the console, `'boxShadow' in document.body.style` and so on. Not just one of the two parts. `in` is a JavaScript operator, it's part of the code.

**Comment by Jojaba** [comment] 2011-11-06 13:58
Oh I see!
Well "true" for 'boxShadow' and "false" for all other properties. As I 
said before, only boxShadow appears in the listed properties I saw. No 
other propertie containing "shadow".

**Comment by LeaVerou** [comment] 2011-11-06 14:00
Thank you!
Can you please run the following commands too?

`'boxShadow' in getComputedStyle(document.body)`
`'msBoxShadow' in getComputedStyle(document.body)`
`'MsBoxShadow' in getComputedStyle(document.body)`

**Comment by Jojaba** [comment] 2011-11-06 14:03
`'boxShadow' in getComputedStyle(document.body)`    >   true
`'msBoxShadow' in getComputedStyle(document.body)`  >   false
`'MsBoxShadow' in getComputedStyle(document.body)`  >   false

**Comment by LeaVerou** [comment] 2011-11-06 15:06
Very, very strange that PF prefixes box-shadow then. I need to get my hands on IE10 somehow and work on it, the issue isn't as simple as I thought.

**Comment by Jojaba** [comment] 2011-11-07 06:42
I try it out with IE9. In this case, no prefixing by -prefix-free and 
the box shadows display...

**Comment by panayiotisa** [comment] 2011-11-07 18:47
free.fr is in the compatibility view list as ie7

if you force ie10 mode everything is ok

**Comment by LeaVerou** [comment] 2011-11-07 21:51
Thanks Panayotis, so relieved!! Joel, can you confirm this please?

**Comment by Jojaba** [comment] 2011-11-08 09:59
```
I try to force IE10 Mode but this doesn't solved the issue for the
free.fr hosting file. You can see it on this screenshot :
When trying on local folder/files, it works ! See the screenshot :
So it should be a problem with free.fr indeed !
Joël
```

[edit]The screenshots are not dipalyed here. I sent them by mail.[/edit]

---

**Comment by LeaVerou** [comment] 2011-11-08 10:00
Great! Closing this issue then. Thank you both.

**Comment by Jojaba** [comment] 2011-11-09 09:03
Really sorry but even on other host the box shadow doesn't display.
See on Alsacreations site: http://www.alsacreations.com/xmedia/tuto/exemples/prefixfree/prefixfree-demo.html

**Comment by LeaVerou** [comment] 2011-11-09 09:04
Reopened, but I don't currently have time to look into it. Will try to have a look this weekend.

**Comment by panayiotisa** [comment] 2011-11-09 20:23
I see that the text encoding of the css file is utf-8 without BOM. I have a strong feeling that this is the culprit.

Save it as ansi or utf-8 with BOM and try again.

**Comment by Jojaba** [comment] 2011-11-10 17:11
I try it with utf-8 and then ansi encoding on free server (I didn't forget to switch to IE10 mode) but nothing changed.
http://jojaba.free.fr/alsacreations/prefixfree-demo/prefixfree-demo.html

**Comment by panayiotisa** [comment] 2011-11-11 18:35
I tested the page on my local apache and I wasn't able to reproduce the issue, prefixfree works as expected.

**Comment by Jojaba** [comment] 2011-11-11 20:37
So you installed IE10. Can you try to look if the following online page 
works?
http://www.alsacreations.com/xmedia/tuto/exemples/prefixfree/prefixfree-demo.html

If yes, then I have certainly a wrong IE10 version...

**Comment by LeaVerou** [comment] 2011-11-11 20:37
I think you mistook panayotisa for me :P

**Comment by Jojaba** [comment] 2011-11-11 20:41
Oh excuse me Lea, I didn't look to the sender... I also saw that 
locally, the page works (what box-shadows belongs of course) but because the JS doesn't worked (so the shadow appears) I don't know why the js files didn't work and why !!!

**Comment by panayiotisa** [comment] 2011-11-13 16:07
I'm afraid I can't help.

**Comment by LeaVerou** [comment] 2011-12-02 03:39
Issue affects box-shadow in general, and every box- property (e.g. box-sizing). Will publish patch soon.

**Closed as completed** 2011-12-02 11:43 UTC
Labels: Fixed
